### ISSUE TITLE
ExtremeInjector has a lot of open handles

### ISSUE THREAD

**Issue by elertan** [master131/ExtremeInjector#10]
I opened my task manager and the process showed to have about 50K of handles, which keeps incrementing by about 500 per second.

![](https://image.prntscr.com/image/2Tt6oUsQQ__ac_60L5aLXw.png)

I doubt this is wanted behavior.

Here is some information about the system:

System Information report written at: 12/06/17 01:44:17
System Name: DENNISKIEVIB634
[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Pro	
Version	10.0.15063 Build 15063	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	DENNISKIEVIB634	
System Manufacturer	Parallels Software International Inc.	
System Model	Parallels Virtual Platform	
System Type	x64-based PC	
System SKU	Undefined	
Processor	Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz, 2295 Mhz, 2 Core(s), 2 Logical Processor(s)	
BIOS Version/Date	Parallels Software International Inc. 13.1.1 (43120), 17/10/2017	
SMBIOS Version	2.7	
Embedded Controller Version	13.01	
BIOS Mode	UEFI	
BaseBoard Manufacturer	Parallels Software International Inc.	
BaseBoard Model	Not Available	
BaseBoard Name	Base Board	
Platform Role	Desktop	
Secure Boot State	Unsupported	
PCR7 Configuration	Binding Not Possible	
Windows Directory	C:\Windows	
System Directory	C:\Windows\system32	
Boot Device	\Device\HarddiskVolume2	
Locale	United States	
Hardware Abstraction Layer	Version = "10.0.15063.502"	
User Name	DENNISKIEVIB634\denniskievits	
Time Zone	W. Europe Standard Time	
Installed Physical Memory (RAM)	2,00 GB	
Total Physical Memory	1,98 GB	
Available Physical Memory	1,14 GB	
Total Virtual Memory	3,10 GB	
Available Virtual Memory	2,25 GB	
Page File Space	1,13 GB	
Page File	C:\pagefile.sys	
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not InstantGo, Un-allowed DMA capable bus/device(s) detected, TPM is not usable	
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by master131** [comment]
Thanks, I'll look into this.
