### ISSUE TITLE
Valorant cheat/Unable to find kernel32.dll

### ISSUE THREAD

**Issue by Etpou** [master131/ExtremeInjector#105]
I am trying to inject a cheat into valorant, which according to my provider should be working with the injector, but trying everything i found i cant seem to find success. My last resort is to try to do a fresh install of windows, but i dont wanna do the whole process ending up it not working anyways.

![ei](https://github.com/master131/ExtremeInjector/assets/164793253/e95ad48b-8c8e-4548-874b-4b56b38afe68)

**Comment by shizamuru-dev** [comment]
Very questionable cheat....

Usually cheats for games with normal anti-cheats (easy, battleye, vanguard and others) use something better than dll.

I advise you to search the Internet for information on "0 ring" cheats. But in brief:

Vanguard ( Valorant Antichit ) works at kernel level and is the "big boss" for all normal programs. No matter how you try, it will always see your injection attempts. It simply "catches" all interactions with memory and if they concern the game, it automatically cuts them off. And because anti-cheat works at the kernel level, you can't interfere with it without your driver.

Ask your driver about a driver that disables anti-cheat or acts as an injector. If it is available, work through it, if not - most likely, you were cheated.

**Comment by Etpou** [comment]
Yea well from what he said the cheat is working trough a windows kernel driver, which boots up sooner than vanguard, so it shouldnt be able to detect it, but im no cheat maker so i cant say for sure.

**Comment by shizamuru-dev** [comment]
Well, then in that case I should ask, did you install the driver? It would be more correct to say did they give it to you?

**Comment by Etpou** [comment]
Sorry for the late response, no i did not install any drivers from them.

**Comment by shizamuru-dev** [comment]
Hmmmm... Ok, did they give you anything other than a .dll file? If yes - you can post the list of files here, it will clarify the problem. If not, you are most likely being scammed

**Comment by BananaEnjoyer09** [comment]
hey i have the same cheat and funnily enough the same problem. 
Im ready to share my files so maybe you could help me with this problem

**Comment by Etpou** [comment]
Here is everything i received
![obrazek](https://github.com/master131/ExtremeInjector/assets/164793253/9557cbfc-0121-4d55-a48c-a5fde5484056)
![obrazek](https://github.com/master131/ExtremeInjector/assets/164793253/22e9c84a-baf9-4eec-8f50-dbf4495bf589)

**Comment by shizamuru-dev** [comment]
Ooooookay, I'm back here again, and I apologize for my tardy responses.

And I have some good news - you have the driver, aka "s.sys"!

I understand roughly what you need to do, but still... Could you please post the README file here?

So, while you're at it, you can try the following:

- First, close all processes related to Valorant ( the game itself, anticheat, launcher, etc ) 
- Then drag the "s.sys" file to "kdmapper" 
- Then try to start Valorant and inject the cheat

If all goes well - you can inject the cheat!

If you get any errors, just attach screenshots of them in the readme.

**Comment by Etpou** [comment]
[README.txt](https://github.com/master131/ExtremeInjector/files/14965899/README.txt)
here it is there is not much, and i tried everything but here you go 

And nope the same thing happened again i did put the s.sys file into kdmapper and it did ask me to give it perms and then nothing happened after that, tried to launch the game but  i had to restart my pc so it could launch vanguard again, and then i tried to inject same thing happened again

**Comment by shizamuru-dev** [comment]
Hmmmmm.... Ok, then try the same thing but without closing vanguard

**Comment by Etpou** [comment]
Nope, sadly the same thing happened again :/

**Comment by shizamuru-dev** [comment]
Ok, then do the following: 
- Download this version of kdmapper - https://www.mediafire.com/file/limnpoeuuajp84m/kdmapper_Debug.exe/file 
- Then disable the "Vulnerable Driver Blocklist" protection ( [video](https://www.youtube.com/watch?v=l2IEKAO1d8c) ) 
- And now also drag and drop s.sys onto the new kdmapper.

**Comment by Etpou** [comment]
ok well i cant download the kdmapper cuz it is blocked by mediafire for being a dangerous file. but i had the "Vulnerable Driver Blocklist" allready off so yea idk what to do next.

**Comment by shizamuru-dev** [comment]
Damn mediafire... Okay... Then try downloading it from Mega - https://mega.nz/file/znBRhaAD#1fYPSL6YrgLaaCm5rdbg7Z09xqNePGLjpVGMWtFiXic

Also, if you have windows defender enabled, I advise you to disable it

**Comment by Etpou** [comment]
Well i just performed a reinstall of windows and still nothing. This was my last resort and i lost interest in using the cheat
