### ISSUE TITLE
Injector is confused when multiple processes with the same name

### ISSUE THREAD

**Issue by danielzyp** [master131/ExtremeInjector#15]
When injecting to processes like csrss, where there are 2 of them, the injector always picks the one with the lower PID value.
Is there anyway to configure it so it will pick the bigger PID value? maybe scan the processes list reversed?

**Comment by master131** [comment]
By default when you search for a process by name it will select the first instance it finds as defined by the OS via the Windows APIs. If you wish to select a process with a specific PID please use the "Select" button.
