### ISSUE TITLE
Combat arms issue

### ISSUE THREAD

**Issue by SassyDog** [master131/ExtremeInjector#17]
Hello master131,

                             I just got extreme injector after hours of searching for a good install. Seems Oldschoolhack.me doesn't have the right one. That's my main site for .dll files. Then i found github.com and noticed you had links to your supported sites so thank you for that very much :). But my problem now is when ever i try to inject in to combatarms which is now combatarms reloaded the game has a pop up saying it detected suspicious programs running and won't let me open the game. I assume it's detecting the injector. I've tried both starting the injector during and before i start the game in safe mode and normal with no luck. Is there anything i can try to avoid the injector from being detected? Side note- Combat arms was run through nexon then switched to VALOFE which seems to have a stronger anti-cheat system from what I've noticed so far.

                                                  Thanks for any help and feedback on this matter. :) 👍

**Comment by Jhovannylv** [comment]
@master131 do you have a new DLL for combat arms the classic?

**Comment by SassyDog** [comment]
I gave up combat arms. No one makes dll for the new version and saddly my
coding knowledge is non exstint so I cant make one

**Comment by Jhovannylv** [comment]
@SassyDog but recently there was a DLL running for this

**Comment by master131** [comment]
I'm afraid I cannot give specific advice on evading anti-cheat detection.
