### ISSUE TITLE
kernel32.dll

### ISSUE THREAD

**Issue by neofatum** [master131/ExtremeInjector#18]
Hi i have a problem when i'm loading dll in the game.
"Unable to find kernel32.dll in the specified process" 

what can i do  ?

i just reinstall the game
and did windows update 
i'm not overclocking 

Thanks for help

**Comment by SaltyTomato** [comment]
My game crashes now when i inject the dll. it worked like a week and half ago. does ur still crash i need help to fix

**Comment by master131** [comment]
Is the process you injecting into anti-cheat protected? It may be preventing proper access required by the injector.

@SaltyTomato Whatever you are injecting might not be compatible anymore. Please contact the author of the DLL you are injecting.

**Comment by neofatum** [comment]
it's ok for me i just understand how it works 
i have to inject when i start the game not when i'm in ...

thanks guys

**Comment by SaltyTomato** [comment]
master did u not make the menu and how do i get the latest one: i'm on v 3.7.2

**Comment by SaltyTomato** [comment]
i tried inject when the game starts up but it still crashes

**Comment by SaltyTomato** [comment]
And can u send me a link to where i can re-download a version of it that u know works?

**Comment by SaltyTomato** [comment]
@neofatum do u have the link to the injector that ur using because my stop working it crashes my game
