### ISSUE TITLE
Injector crashing game

### ISSUE THREAD

**Issue by SaltyTomato** [master131/ExtremeInjector#19]
I replied on the other issues, can someone send me v 3.7.3  or v 3.7.3

**Comment by SaltyTomato** [comment]
@Night3lf do u know if this one will work rn if I inject it into GTA 5? Will it not crash my game. Does it work for u

**Comment by Night3lf** [comment]
@SaltyTomato, typically with this injector if the game crashes, it is the cheat you are using. This is not always true but this is just typically what happens. There is no way to tell until you try.

**Comment by SaltyTomato** [comment]
Did it work for u still

**Comment by Night3lf** [comment]
@SaltyTomato The injector works without an issue for me on many games.

**Comment by SaltyTomato** [comment]
@Night3lf thank u so much for ur help

**Comment by Night3lf** [comment]
@SaltyTomato No problem, hmu if you need something else. :)

**Comment by SaltyTomato** [comment]
@Night3lf  k thx

**Comment by SaltyTomato** [comment]
@Night3lf it still crashes. should i use the dll that game with the old injector or can u send me the new dll i can inject into the game?

**Comment by Jhovannylv** [comment]
I also close the game, is there a new dll?

**Comment by SaltyTomato** [comment]
@Jhovannylv u having the same problem as me?

**Comment by Jhovannylv** [comment]
@SaltyTomato Yes, since the last update stopped working

**Comment by SaltyTomato** [comment]
@Jhovannylv @Jhovannylv @master131 i know, what did they do. i got v3.7.3 but i need the new dlls

**Comment by Jhovannylv** [comment]
@SaltyTomato I also need a new dll for combat arms

**Comment by SaltyTomato** [comment]
@Jhovannylv do u now anyone at all that has working dlls for gta 5 online

**Comment by Jhovannylv** [comment]
no, do you know someone who has dlls to Combat arms the classic?

**Comment by master131** [comment]
This is getting off topic, DLLs specific to a game should not be discussed here.
