### ISSUE TITLE
commandline

### ISSUE THREAD

**Issue by fisherprice84** [master131/ExtremeInjector#2]
hi friend, do you have Email i can make contact?  thanks

**Comment by master131** [comment]
Shoot me a PM here:
http://www.mpgh.net/forum/member.php?u=539054

**Comment by fisherprice84** [comment]
Hi, I can't private message you there.  I am looking to see if you sell any
versions of extreme injector where the manual mapping can be commandline.
Thanks

**Comment by master131** [comment]
No, I do not sell custom builds of Extreme Injector. Please consider looking at other great OSS projects such as Xenos/Blackbone on Github.

https://github.com/DarthTon/Xenos
