### ISSUE TITLE
Extreme Injector v3 Instant Crash 

### ISSUE THREAD

**Issue by gorgonzolla2** [master131/ExtremeInjector#21]
When i click on it, it just appears for a moment in task manager then it disappears
pls help me fix this

**Comment by Abadima** [comment]
the similar thing happens to me! every time I inject the DLL into the roblox game it crashes!!!

**Comment by master131** [comment]
Make sure you are using the latest version, see here (the MPGH mirror):
https://github.com/master131/ExtremeInjector

**Comment by 0xKizuma88D3D** [comment]
SAME SHIT
