### ISSUE TITLE
FIFA 18 extreme injector stuck on ronaldo waiting screen before language

### ISSUE THREAD

**Issue by Malin20** [master131/ExtremeInjector#22]
Hey can you help me to fix it ? Im stuck on ronaldo waiting screen before choosing language. I really dont wanna wait 5 minutes

**Comment by Malin20** [comment]
@master131  why y closed the issue you didint help me?

**Comment by master131** [comment]
This has nothing to do with the injector. This is a problem with whatever you are injecting, go contact the author of that DLL.

**Comment by Malin20** [comment]
i throug that you were the author where i can contact him?
