### ISSUE TITLE
Extreame Injector v3.7.2 Roblox Crash

### ISSUE THREAD

**Issue by Abadima** [master131/ExtremeInjector#24]
every time I load my DLL into the roblox game my roblox crashes like this:

![error 2](https://user-images.githubusercontent.com/39747270/40687438-9b0199a0-6368-11e8-92e5-bd6fd8fc6c05.JPG)

and also for the full screen:

![error](https://user-images.githubusercontent.com/39747270/40687486-ca3ee240-6368-11e8-88bb-6387c2f43623.JPG)

Please Fix This Error Please Respond By Email:
abadima06@gmail.com

**Comment by TypicalNevin** [comment]
It means that the dll is patched
