### ISSUE TITLE
hi i find bug

### ISSUE THREAD

**Issue by alimansuri0** [master131/ExtremeInjector#25]
hi.

I open a game called Zula and I tried to inject it a DLL. But I did not find it in your program.
and this game support by battleeye. pleas tel me for what : alimansuri1544@gmail.com

**Comment by alimansuri0** [comment]
![capture](https://user-images.githubusercontent.com/39797628/40880497-673af654-66c7-11e8-8b02-695e92826166.JPG)

**Comment by westclox410** [comment]
Я играю в игру "Rules of Survival" и я использовал ваш чит Extreme Injector v3.7.3 by master131.
После обновления от 15.08.2018 чит стал отображаться НЕ правильно, рядом с машиной персонаж стал исчезать а через стены видно только оружие и то не всегда. Можешь сделать фикс и дать новую версию? что бы донести тебе об этом пришлось зарегистрироваться на этом форуме\сайте. 
Буду благодарен если отреагируешь)

**Comment by westclox410** [comment]
Я играю в игру «Правила выживания» и я использовал ваш чит Extreme Injector v3.7.3 by master131. 
wallhack KkK1337 
После обновления от 15.08.2018 чит стал отображаться НЕ правильно, рядом с машиной персонаж стал беспрестанно. Можешь сделать фикс и дать новую версию? что бы донести вам это на 2 года. 
Буду благодарен если отреагируешь)

**Comment by master131** [comment]
BattleEye hides the processes of games to prevent injection, try auto-inject or find an alternative method for injection.
