### ISSUE TITLE
ExtremeInjector is apparently detected by VAC

### ISSUE THREAD

**Issue by wardinh0** [master131/ExtremeInjector#26]
Just got VACed in one of my accounts. The DLL is still safe, I use it in other accounts with other injectors and they're fine.

Please, share the source code so we can add some junk code, there is no much point in sharing freeware without the source code.

**Comment by Eyremba** [comment]
> Please, share the source code so we can add some junk code

You can also just crypt the .exe file (the injector) with some tools and/or pack it again to change its hashes and signatures.

**Comment by M1XT3NZ** [comment]
or you could just use the secure mode like every normal guy should....

**Comment by Eyremba** [comment]
> or you could just use the secure mode like every normal guy should....
Doesn't this only change the name of the .exe file in the process list and the name of the window?
VAC works with process-fingerprints / some sort of hashes, and maybe they don't change.

**Comment by M1XT3NZ** [comment]
so i use extreme since 1-2 years and turned secure mode on like 6 months ago all the time. (you also need a usb or veracrypt and you everything is undetected ;) you dont inject ingame anyway)
settings i use http://prntscr.com/kdn4xm

**Comment by Ashley-star** [comment]
Pls give us source we need add junk code

**Comment by master131** [comment]
Extreme Injector is not guaranteed to be VAC safe - use at your own risk. Also keep in mind that VAC can also detect hack signatures too.
