### ISSUE TITLE
About your long-lost masterpiece -- Black Ops Sound Studio

### ISSUE THREAD

**Issue by Lee-berty** [master131/ExtremeInjector#30]
Hello master131, I don't know whether it is polite to ask about an unmatched tool you published on Itsmods.com, which is BLACK OPS II/III Sound Studio. 

The reCAPTCHA for itsmods has been shutdown for a while so nobody get to register a new account or login from a new IP address. 

So could you kindly release the BLACK OPS II/III Studio here on github? 

Or can you send it to michaelangello@163.com (my email) in case the tool may get noticed by Activision lol. 

It would be vert nice of you. 

Btw I am a modder for BF2, and I've made sth interesting with python and C#, see here lol : 
https://www.youtube.com/channel/UCB1oEz30GuNbnf9lv2-eo7Q/videos?view_as=subscriber

**Comment by master131** [comment]
See the repository below:
https://github.com/master131/Black-Ops-II-Sound-Studio
