### ISSUE TITLE
Wont Inject

### ISSUE THREAD

**Issue by oofof** [master131/ExtremeInjector#31]
It doesnt seem to inject and I have done everything. Can I have some help please. Thanks

**Comment by master131** [comment]
What are you trying to inject? What method are you using? Chances are that you need to consult the author of the DLL you are trying to inject as it's a problem with the DLL rather than the injector itself.

**Comment by oofof** [comment]
I know there is nothing wrong with the dll because my friend is using the same one as me. The method I am using is literally what I have to do. The dll is esp https://www.wearedevs.net/d/ESP

**Comment by oofof** [comment]
I have done it
Just had to wait a day :P Have a nice day and thanks for your help.
