### ISSUE TITLE
Sk8r Injection Problems

### ISSUE THREAD

**Issue by GarlicBread10** [master131/ExtremeInjector#32]
When I selected sk8r and put the DarkClub.dll and inject says can not so I put others and said cannot so I hit ok and it said injected and when I exclude nothing no nofications on roblox that I injected it

**Comment by master131** [comment]
This is out of the scope of the injector, it's probably a problem with the DLL you are injecting - please consult the author.

**Comment by kodyfos** [comment]
When i'm downloading, it included a virus.
