### ISSUE TITLE
How download ExtremeInjector?

### ISSUE THREAD

**Issue by 1CryBaby1** [master131/ExtremeInjector#33]
How download ExtremeInjector? Help me pls! I have 8 WinRar, so, what i should to do then?
![image](https://user-images.githubusercontent.com/54374568/63460454-f9085e80-c46f-11e9-8133-54531b9e9caa.png)

**Comment by GazziFX** [comment]
You should download from unknowncheats.me

**Comment by colin1118** [comment]
MPGH link doesn't work and the 3.7.3 version on Unknowncheats.me download link was removed by staff, would it be possible to get a new link for 3.7.3 version? Thank you.
![link gone](https://user-images.githubusercontent.com/52926749/64321299-4ca99a80-cf8e-11e9-815f-5c3829bc1bba.jpg)

**Comment by master131** [comment]
I've updated the README with new links including a Github mirror.
