### ISSUE TITLE
Please help!!

### ISSUE THREAD

**Issue by SSUpera** [master131/ExtremeInjector#37]
Hello, producer of "Extreme Injector." 

The reason why I am sending this email is because I am also making an injector.

When my injector is shut down and re-run, I have to select "Dll" again through Openfiledialog in the path and folder where the injector is stored and inject it.

I want to keep the "dll" file that I once grabbed like "Extreme Injector" even if I turn the injector back on, but it's hard for me to code.

I ask for your help.

**Comment by SSUpera** [comment]
I working VB

**Comment by master131** [comment]
This has nothing to do with the injector itself; please ask on a relevant site like StackOverflow or programming-related forum.
