### ISSUE TITLE
Extreme Injector v3.7 Instant Crash (Windows 10)

### ISSUE THREAD

**Issue by jakey1995abc** [master131/ExtremeInjector#4]
Hi, I am running the latest Windows 10 64 bit insider build 17004.1000 and have noticed that for some reason, all of your extreme injectors v3 and onwards instantly crash when opened. The only version I have found that works is V2, but that is way outdated now. I was wondering if you know what could be causing this or how it could be fixed? I have installed all dependencies and verified windows files with sfc , dism, chkdsk but none of them seem to have fixed it.

**Comment by master131** [comment]
I have not tested it using the Insider Builds; but its strange that it crashes upon start. There could be some internal change to OS structures that the injector doesn't like. I'll get an insider build running on a VM and investigate further.

**Comment by master131** [comment]
So after some investigation, it appears one undocumented API that Extreme Injector uses was changed in the latest .NET Framework. I will fix this immediately and push out an update soon.

Thanks again for the bug report.
