### ISSUE TITLE
windows 10 Failed - Virus detected

### ISSUE THREAD

**Issue by hamadfayyad** [master131/ExtremeInjector#40]
I try to download but  Failed - Virus detected
Windows Defender Firewall is off

**Comment by ghost** [comment]
it doesnt matter if the firewall is off disable realtime protection and it gets detected because of dll injectors arent window's favorites

**Comment by AlcorSalvador** [comment]
Thats funny, because 3.7.2 doesnt do that. 3.7.3 is a legit Virus

**Comment by ghost** [comment]
> Thats funny, because 3.7.2 doesnt do that. 3.7.3 is a legit Virus

no? likely just using a detected injection method which wont be changed since by the looks of it master has moved on

**Comment by master131** [comment]
It's a false positive; Extreme Injector v3.7.3 has been on the internet for 3 years now - its the latest version so its more likely to be picked up by anti-virus software as a hack tool compared to v3.7.2.

Don't you think there would be more warnings on the internet if it was truly a virus? :man_facepalming:
