### ISSUE TITLE
Load Libray return NUll in the target process

### ISSUE THREAD

**Issue by Qizour** [master131/ExtremeInjector#46]
An error occurred while injecting "test.dll" into "FallGuys_client.exe" 

System.Exception: LoadLibrary returned NULL in the target process

System.ComponentModel.Win32Exception: 找不到指定的模块.

can u help me  
![QQ截图20200908010117](https://user-images.githubusercontent.com/57248289/92408158-3f118c80-f16f-11ea-8675-16c73019a222.png)

**Comment by master131** [comment]
It means you are probably missing a system DLL that is required by PhantomCheats.dll; check with the developer for the requirements.
