### ISSUE TITLE
Any chance of releases here?

### ISSUE THREAD

**Issue by sidspyker** [master131/ExtremeInjector#6]
Any chance of there being releases here on GitHub? Having to scour MP hack forums is not very fun and relies on staff approval.

I use it for injecting freecam dlls in some games so I don't really belong on a hacks forum.

**Comment by master131** [comment]
Posting releases on Github unfortunately would prevent me from posting them on those forums due to stringent approval rules. It's a bit of a compromise I have to make. Currently it's already approved on MPGH, I'll see what I can do about UC.
