### ISSUE TITLE
Failed To Find Pattern

### ISSUE THREAD

**Issue by SimplyWoke** [master131/ExtremeInjector#67]
Said to contact dev 
![image](https://user-images.githubusercontent.com/58061322/127678927-6afc0abe-6d42-4927-b96c-1131b0aafbc3.png)

**Comment by im-fin** [comment]
Pattern signature didnt work. Try manual injection instead.

**Comment by master131** [comment]
This message is not from Extreme Injector; contact the creator of the DLL.

**Comment by im-fin** [comment]
amogus
