### ISSUE TITLE
not able to run on a virtual machine

### ISSUE THREAD

**Issue by Popthatmodz** [master131/ExtremeInjector#7]
cant run on a virtual machine

**Comment by master131** [comment]
I need more information than that - what operating system? It does indeed run on a virtual machine, I've tested it on Windows 7, 8 and 10 on VMWare and VirtualBox.

**Comment by Popthatmodz** [comment]
Windows 10 and I use a gaming virtual machine called liquid sky

**Comment by Popthatmodz** [comment]
This is what it says it it the dll that's says that or the injector

**Comment by master131** [comment]
That sounds like anti-VM protection on the DLL you are injecting, this has nothing to do with Extreme Injector.
