### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by matarife123** [master131/ExtremeInjector#89]
When I download the file my antivirus warns
![Sin título](https://user-images.githubusercontent.com/110930030/219853196-4abceb85-0dac-4f37-950c-b37339f3cf8c.png)

**Comment by Mystery24601** [comment]
That's because it's known for being able to inject dll's into programs. which is it's intended purpose after all.

**Comment by ExoveDev** [comment]
yes very virus it hacke you retarded monkey

**Comment by Mystery24601** [comment]
Bro that was a long ass time ago, you did not need to reply back like an even bigger retarded monkey

On July 12, 2023 9:34:50 PM GMT+02:00, ExoveDev ***@***.***> wrote:
>yes very virus it hacke you retarded monkey
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/master131/ExtremeInjector/issues/89#issuecomment-1633099713
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- Sent from /e/OS Mail.
