### ISSUE TITLE
Fortnite

### ISSUE THREAD

**Issue by zoebenson31** [master131/ExtremeInjector#9]
Hello master , when i want to inject a dll file that said that ( i have verified i'm in 64bits and my process too , my game launch in 64 bits admin ) can u help me ? 
![unknown](https://user-images.githubusercontent.com/33723865/32894552-6602be9c-cadd-11e7-9963-fe72d2317d10.png)

**Comment by zoebenson31** [comment]
![image](https://user-images.githubusercontent.com/33723865/32894963-c05fcabe-cade-11e7-9cff-46980ab43d19.png)

**Comment by master131** [comment]
This seems like a common problem amongst various injectors on Fortnite due to it's anti-cheat. Have you tried the auto-inject option and started the injector before the game starts?

**Comment by flux3213** [comment]
i have the same problem tried auto injecting and opening the injector before the game started

**Comment by MrGoodBoy228** [comment]
I have the same problem

**Comment by MrGoodBoy228** [comment]
![default](https://user-images.githubusercontent.com/34318606/33682434-80bcd4e2-dad8-11e7-82d6-8be674062455.png)

**Comment by westo6922** [comment]
Do you know how to fix it? Or is it something that cant be bypassed?

**Comment by master131** [comment]
It cannot be bypassed, this is mainly due to BattleEye.
