### ISSUE TITLE
Does not run in WINE or Proton(ge)

### ISSUE THREAD

**Issue by TeN41k** [master131/ExtremeInjector#93]
I tried running Extreme Injector via WINE (Steam Proton GE) (namely via ProtonTricks).
Tried running after installing VC 2015 and .NET 4 and nothing(
Let me know if this problem has already been solved, I did not find it in the search (Github, Youtube, Google search).
Tried through Cheat Engine (downloaded and launched ceserver and was only able to inject in one way, and I need LdrLoadDLLStub) and nothing again.
Distro im using : PoP! OS 22.04 LTS
Session : X11
Proton ver. : GE-Proton-8.4
Thank you for reading the message, i really appreciate that.

**Comment by master131** [comment]
It's not designed to run on Wine. The injector relies on lots of internal and undocumented structures and functions which will mean there will be compatability issues. .NET 4 also has poor support under Wine (unlike newer versions which are Linux native).

**Comment by TeN41k** [comment]
So is any alternatives i can use on linux with wine proton? Let me know please

**Comment by master131** [comment]
I don't know of any injectors that claim to be Wine compatible, you'll have to do research.

**Comment by TeN41k** [comment]
Ok, thank you for the support.
