### ISSUE TITLE
Source code of Extreme Injector. 

### ISSUE THREAD

**Issue by pingwin840** [master131/ExtremeInjector#96]
Hello. I wanted to ask you for the source code for Extreme Injector. What is the problem? I'm studying at the university on GameDev. But, there was a problem. For an important reason, I was forced to skip several lessons. And I was told that in order to get a normal grade, you need to write an anti-cheat. And for this I need the source code of some Injector. I understand that this program is closed source, but I really need it. I'm sorry to trouble you.

**Comment by master131** [comment]
There are plenty of injector references on the internet that are open-source:
https://github.com/topics/dll-injector
